nohup ../loki-linux-amd64 \
-config.expand-env=true \
-config.file=../loki-config.yaml \
-server.http-listen-port=3100 \
-server.grpc-listen-port=9075 \
-memberlist.nodename=backend-01 \
-memberlist.advertise-addr=10.1.39.192 \
-memberlist.advertise-port=7946 \
-memberlist.bind-port=7946 \
-target=backend \
-legacy-read-mode=false &
